name: learn-github-workflows
on: [push]
jobs:
  does-something:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install --update
      - run: aws --version
